SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID!= ALL(SELECT DEPARTMENT_ID FROM EMPLOYEES);
SELECT EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE FROM EMPLOYEES, JOBS WHERE EMPLOYEES.DEPARTMENT_ID = ALL(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE 'Himuro') AND EMPLOYEES.JOB_ID = JOBS.JOB_ID ;
SELECT * FROM EMPLOYEES WHERE JOB_ID = ALL(SELECT JOB_ID FROM JOBS WHERE JOB_TITLE LIKE 'Sales Manager') ORDER BY HIRE_DATE ASC FETCH FIRST 1 ROWS ONLY;
SELECT department_id, (SELECT EMPLOYEE_ID FROM EMPLOYEES e WHERE e.DEPARTMENT_ID =d.DEPARTMENT_ID ORDER BY HIRE_DATE DESC FETCH FIRST 1 ROWS ONLY) EMPLOYEE_ID, (SELECT HIRE_DATE FROM EMPLOYEES e WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID 
ORDER BY HIRE_DATE DESC FETCH FIRST 1 ROWS ONLY) HIRE_DATE FROM DEPARTMENTS d WHERE EXISTS(SELECT department_id from employees p WHERE p.department_id = d.department_id) ORDER BY HIRE_DATE; 
SELECT * FROM EMPLOYEES e WHERE SALARY > (SELECT (MIN_SALARY+MAX_SALARY)/2 FROM JOBS WHERE j.JOB_ID=e.JOB_ID) ;
SELECT LAST_NAME, SALARY FROM EMPLOYEES e WHERE MANAGER_ID IS NOT NULL AND SALARY >(SELECT SALARY*0.75 FROM EMPLOYEES m WHERE m.EMPLOYEE_ID=e.MANAGER_ID) ;
SELECT * FROM DEPARTMENTS d WHERE DEPARTMENT_ID != all(SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID) ;
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES) ORDER BY SALARY DESC FETCH FIRST 3 ROWS ONLY ;
SELECT COUNT(*) EMPLOYEES , EXTRACT(YEAR FROM HIRE_DATE) YEAR FROM EMPLOYEES GROUP BY EXTRACT(YEAR FROM HIRE_DATE) ORDER BY EMPLOYEES DESC ;
SELECT LAST_NAME, (SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEES s WHERE s.MANAGER_ID=e.EMPLOYEE_ID) AVG, (SELECT MAX(SALARY) FROM EMPLOYEES) MAX FROM EMPLOYEES e where exists (select manager_id from departments d where
d.manager_id=e.employee_id); 
SELECT LAST_NAME, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID) DEPARTMENT_NAME from employees; 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, (SELECT LAST_NAME FROM EMPLOYEES e WHERE d.MANAGER_ID=e.EMPLOYEE_ID ) lAST_NAME FROM DEPARTMENTS d WHERE (SELECT COUNTRY_NAME FROM COUNTRIES c WHERE c.COUNTRY_ID=(SELECT COUNTRY_ID FROM
LOCATIONS l WHERE d.location_id=l.location_id)) = 'United Kingdom' or (SELECT COUNTRY_NAME FROM COUNTRIES c WHERE c.COUNTRY_ID=(SELECT COUNTRY_ID FROM LOCATIONS l WHERE d.location_id=l.location_id)) = 'Germany' ;
