SELECT REGIONS.REGION_NAME, COUNTRIES.COUNTRY_NAME FROM REGIONS JOIN COUNTRIES ON 
REGIONS.REGION_ID=COUNTIRES.REGION_ID ORDER BY REGIONS.REGION_ID ASC;

SELECT LOCATIONS.*, DEPARTAMENTS.DEPARTAMENT_NAME FROM LOCATIONS JOIN DEPARTMENTS ON 
DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID ORDER BY LOCATIONS.STATE_PROVINCE ASC;

SELECT EMPLOYEES.* FROM EMPLOYEES JOIN DEPARTMENTS ON 
DEPARTMENTS.DEPARTMENT_NAME LIKE 'Finance' JOIN JOBS ON EMPLOYEES.SALARY > (1.20 * JOBS.MIN_SALARY) AND EMPLOYEES.JOB_ID = JOBS.JOB_ID;

SELECT MAX(EEMPLOYEES.SALARY), '-' , MIN(EMPLOYEES.SALARY), '=', (MAX(EMPLOYEES.SALARY)-MIN(EMPLOYEES.SALARY))
FROM EMPLOYEES, DEPARTMENTS WHERE DEPARTMENTS.DEPARTMENT_NAME LIKE 'FINANCE';

SELECT EMPLOYEES.LAST_NAME FROM EMPLOYEES JOIN DEPARTMENS ON
EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.MANAGER_ID AND DEPARTMENTS.department_name = 'Human Resources';

SELECT EMPLOYEES.LAST_NAME, DEPARTMENTS.DEPARTMENT_NAME FORM EMPLOYEES JOIN
DEPARTMENTS ON EMPLYESS.DEPARTMENT_ID LIKE DEPARTMENTS.DEPARTMENT_ID JOIN JOBS ON JOBS.JOB_TITLE LIKE 'Sales Manager' AND EMPLOYEES,JOB_ID = JOBS.JOB_ID;

SELECT EMPLOYEES.LAST_NAME, REGIONS.REGION_NAME FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID JOIN
LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID JOIN REGIONS ON COUNTRIES.REGION_ID LIKE REGIONS.REGION_ID;

SELECT JOBS.JOB_TITLE, JOBS.MIN_SALARY FROM JOBS JOIN JOB_HISTOR ON JOB_HISTORY.JOB_ID
LIKE JOBS.JOB_ID JOIN EMPLOYEES ON JOB_HISTORY.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID AND EMPLYEES.LAST_NAME LIKE 'Hunold';

SELECT EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_ID,DEPARTMENTS.DEPARTMENT_NAME FROM EMPLYEES JOIN JOBS ON EMPLOYEES.JOB_ID LIKE
JOBS.JOB_ID JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEOARTNEBTS.DEPARTMENT_ID;

SELECT EMPLYEES.LAST_NAME, DEPARTMENTS.DEPARTMENT_NAME,LOCATIONS.STREET_ADDRESS FROM EMPLYEES JOIN DEPARTMENTS ON
EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID JOIN LOCATIONS ON DEPARTMETS.LOCATION_ID = LOCATIONS.LOCATION_ID;

SELECT E1.LAST_NAME AS "pracownik", E2.LAST_NAME AS "manager" FRPM EMPLOYEES E1 JOIN EMPLOYEES E2 ON
E1.EMPLOYEE_ID = E2.MANAGER_ID WHERE E1.SALARY > 4000 AND E1.SALARY <7000 ORDER BY E1.LAST_NAME DESC;

SELECT E.LAST_NAME, J.JOB_TITLE, E.SALARY AS SALARY_PER_MONTH, J.MIN_SALARY, J.MAX_SALARY, D.DEPARTMENT_NAME FROM EMPLOYEES E
JOIN JOBS J ON J.JOB_ID = E.JOB_ID JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPRATMENT_ID WHERE J.JOB_TITLE = 'IT Helpdesk' ORDER BY E.SALARY DESC;
